version: '3.1'

services:
  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "shortyUrl"
      MYSQL_PASSWORD: "root"
    volumes:
      - "./sql/init.sql:/docker-entrypoint-initdb.d/init.sql"
      - "./mariadb/data:/var/lib/mysql/data/"
      - "./mariadb/logs:/var/lib/mysql/logs/"
    ports:
      - "3306:3306"


  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 8181:80
    environment:
      - PMA_ARBITRARY=1