CREATE DATABASE IF NOT EXISTS shortyUrl;

USE shortyUrl;

CREATE TABLE IF NOT EXISTS url
(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    longUrl VARCHAR(255)
);

ALTER TABLE url AUTO_INCREMENT = 56800235584;